config/routes.rb
Smellybean::Application.routes.draw do
  resources :movies
  match'/movies/show_director/:id' => 'movies#show_director', :as => :show_director

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :title, :rating, :description, :release_date, :director
  def self.all_ratings ; %w[G PG PG-13 R] ; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def show
    id = params[:id] # retrieve movie ID from URI route
    @movie = Movie.find(id) # look up movie by unique ID
    # will render app/views/movies/show.<extension> by default
  end
  
  def index
    @new_order = params[:order].present?
    @new_filter = params[:ratings].present?
    @session_order = session[:order].present?
    @session_ratings = session[:ratings].present?
    @all_ratings = Movie.all_ratings
    @redirect = false 
    if @new_order
      session[:order] = params[:order]
    elsif @session_order
      redirect = true 
    end 
    
    if session[:ratings] == nil
      @init_hash = Hash.new()
      @all_ratings.each{|rating| @init_hash[rating] = 1}
      session[:ratings] = @init_hash  
    elsif @new_filter   
      session[:ratings] = params[:ratings]     
    elsif @session_ratings
      redirect = true 
    end 
    if redirect
      flash.keep
      redirect_to(movies_path(:order => session[:order], :ratings => session[:ratings]))
    else 
      @checked = session[:ratings].keys 
      @order = session[:order]
      @movies = Movie.order(session[:order])
      @movies =  @movies.find_all_by_rating(@checked) 
    end    
  end

  def new
    # default: render 'new' template
  end

  def create
    @movie = Movie.create!(params[:movie])
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    @movie.update_attributes!(params[:movie])
    flash[:notice] = "#{@movie.title} was successfully updated."
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:notice] = "Movie '#{@movie.title}' deleted."
    redirect_to movies_path
  end

  def show_director 
    @movie = Movie.find(params[:id])
    @director = @movie.director
    if @director.nil? || @director.empty?
      flash[:notice] = "'#{@movie.title}' has no director info."
      redirect_to movies_path 
    else 
      # @director = @movie.director
      @movies = Movie.find_all_by_director(@director) 
    end 
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
%html
  %head
    %title Smelly Bean!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %h1.title Smelly Bean!
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

      = yield

app/views/movies/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Movie

= form_tag movie_path(@movie), :method => :put do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :director, 'Director'
  = text_field :movie, 'director'

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Update Movie Info'

app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 All Movies

= form_tag movies_path, :method => :get, :id => 'ratings_form' do 
  Include: 
  - @all_ratings.each do |rating|
    = rating
    = check_box_tag "ratings[#{rating}]", rating, @checked.include?(rating), :id => "ratings_#{rating}"
  = submit_tag 'Refresh', id: 'ratings_submit'
%table#movies
  %thead
    %tr
      %th{:class => ("hilite" if @order == 'title')}= link_to "Movie Title", movies_path(:order => 'title', :ratings => params[:ratings]), :id => 'title_header'
      %th Rating
      %th{:class => ("hilite" if @order == 'release_date')}=link_to "Release Date", movies_path(:order => 'release_date', :ratings => params[:ratings]), :id => 'release_date_header'
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Add new movie', new_movie_path

app/views/movies/new.html.haml
%h1 Create New Movie

= form_tag movies_path do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Save Changes'

app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

%h2 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")
  %li 
    Director:
    = @movie.director

%h3 Description:

%p#description= @movie.description
= link_to 'Find Movies With Same Director', show_director_path(@movie)
/ - if @movie.director.nil? || @movie.director.empty?
/   -flash[:warning] = "'#{@movie.title}' has no director info."
/   = link_to 'Find Movies With Same Director', movies_path
/ - else
/   = link_to 'Find Movies With Same Director', show_director_path(@movie)
= link_to 'Edit', edit_movie_path(@movie)
= button_to 'Delete', movie_path(@movie), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to movie list', movies_path

app/views/movies/show_director.html.haml
%h1 Movies directed by #{@movie.director}
/ = form_tag movies_path, :method => :get, :id => 'ratings_form' do 
/   Include: 
/   - @all_ratings.each do |rating|
/     = rating
/     = check_box_tag "ratings[#{rating}]", rating, @checked.include?(rating), :id => "ratings_#{rating}"
/   = submit_tag 'Refresh', id: 'ratings_submit'
%table#movies
  %thead
    %tr
      %th Movie Title
      %th Rating
      %th Release Date
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Back to movie list', movies_path